// File generated by FlutterFire CLI & configured for multi-environment (dev / prod).
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:balance/core/config/app_environment.dart';

/// Default [FirebaseOptions] for use with your Firebase apps across Dev and Prod environments.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  /// Returns the Android [FirebaseOptions] corresponding to the active runtime environment.
  static FirebaseOptions get android =>
      AppEnvironment.isDev ? androidDev : androidProd;

  /// Development environment Android Firebase options (`com.ekerstudio.balance.debug`).
  static const FirebaseOptions androidDev = FirebaseOptions(
    apiKey: 'AIzaSyCylVV_NlDt7B71RsmKmeisDw7NqXZPl74',
    appId: '1:362421637114:android:ca1fee7d985e0d1300de43',
    messagingSenderId: '362421637114',
    projectId: 'balance-weight-tracker',
    storageBucket: 'balance-weight-tracker.firebasestorage.app',
  );

  /// Production environment Android Firebase options (`com.ekerstudio.balance`).
  static const FirebaseOptions androidProd = FirebaseOptions(
    apiKey: 'AIzaSyCylVV_NlDt7B71RsmKmeisDw7NqXZPl74',
    appId: '1:362421637114:android:5b8e972ee5fc105000de43',
    messagingSenderId: '362421637114',
    projectId: 'balance-weight-tracker',
    storageBucket: 'balance-weight-tracker.firebasestorage.app',
  );

  /// Returns the iOS [FirebaseOptions] corresponding to the active runtime environment.
  static FirebaseOptions get ios => AppEnvironment.isDev ? iosDev : iosProd;

  /// Development environment iOS Firebase options (`com.ekerstudio.balance.debug`).
  static const FirebaseOptions iosDev = FirebaseOptions(
    apiKey: 'AIzaSyANdThXIcc-PbdwXG2FZ-QoV5s03YRxMAU',
    appId: '1:362421637114:ios:2f8b66cbda81bfd200de43',
    messagingSenderId: '362421637114',
    projectId: 'balance-weight-tracker',
    storageBucket: 'balance-weight-tracker.firebasestorage.app',
    iosBundleId: 'com.ekerstudio.balance.debug',
  );

  /// Production environment iOS Firebase options (`com.ekerstudio.balance`).
  static const FirebaseOptions iosProd = FirebaseOptions(
    apiKey: 'AIzaSyANdThXIcc-PbdwXG2FZ-QoV5s03YRxMAU',
    appId: '1:362421637114:ios:3ecf49e83386f20600de43',
    messagingSenderId: '362421637114',
    projectId: 'balance-weight-tracker',
    storageBucket: 'balance-weight-tracker.firebasestorage.app',
    iosBundleId: 'com.ekerstudio.balance',
  );
}
